name: CI

on: [push, pull_request]

jobs:
  codestyle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint:ci

  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: pnpm typecheck

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 9.12.1
      - uses: actions/setup-node@v4
        with:
          node-version: 20.18.0
          cache: 'pnpm'
      - run: pnpm i --frozen-lockfile
      - run: echo "${{ vars.ENV }}" >> .env
      - run: pnpm test
